server:
  port: 9101
spring:
  application:
    name: iacaa_analysis
  cloud:
    nacos:
      discovery:
        server-addr: 47.108.28.239:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.108.28.239:3308/iacaa20?rewriteBatchedStatements=true&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.qingfeng.analysis.beans

#查看mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


