server:
  port: 9101
spring:
  application:
    name: iacaa_analysis
  cloud:
    nacos:
      discovery:
        server-addr: 47.108.28.239:8848
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.108.28.239:3308/iacaa20?rewriteBatchedStatements=true&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: root
      max-active: 20
      initial-size: 3
      min-idle: 5

#查看mybatis日志
mybatis-plus:
  mapper-locations: classpath:mappers/*Dao.xml
  type-aliases-package: com.qingfeng.analysis.beans
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


